[entrypoint]
command = ["python3", "admin_app_workflow.py"]
port = 5000
autoload = true
keepPreviousOutputs = true
show_restart_notification = false
private = false
preview = true

[hints]
restart = "Enable/Disable Admin Mode for Development"