# App Workflow Configuration
command = "python app_workflow.py"
clearOnRestart = false
restartPolicy = "on-failure"
onBoot = true

[env]
# Environment variables for main application server
PYTHONUNBUFFERED = "1"  # Unbuffered output for better logging
PORT = "5000"           # Port for the Flask server