# Flask Application Workflow
run = "python flask_workflow.py"
language = "python"
entrypoint = "flask_workflow.py"
onBoot = "python -c 'from flask_workflow import run; run()'"
hidden = false

[nix]
channel = "stable-22_11"

[env]
PYTHONPATH = "."
PORT = "5000"
PYTHONUNBUFFERED = "1"

[languages]

[languages.python]
pattern = "**/*.py"

[languages.python.languageServer]
start = "pylsp"