# Job Worker Workflow Configuration
# This workflow runs the background job processing system

command = "python job_worker_workflow.py --workers 2 --queues high,default,low,email,indexing"

[env]
# Number of worker processes to run
WORKER_COUNT = "2"

# Queue names to listen on (in priority order)
QUEUE_NAMES = "high,default,low,email,indexing"

# Redis connection parameters
REDIS_HOST = "my-bullmq-cache.redis.cache.windows.net"
REDIS_PORT = "6380"
REDIS_SSL = "true"
# Redis password is stored in environment secrets