# Job Worker Workflow Configuration
command = "python job_worker_workflow.py"
clearOnRestart = false
restartOn = ["job_worker_workflow.py", "jobs.py", "worker.py", "job_worker.py"]
restartPolicy = "on-failure"
onBoot = true

[env]
# Environment variables for job worker
PYTHONUNBUFFERED = "1"  # Unbuffered output for better logging
WORKER_TIMEOUT = "300"  # Worker timeout in seconds
JOB_RESULT_TTL = "604800"  # Job result TTL in seconds (7 days)
FAILED_JOB_TTL = "2592000"  # Failed job TTL in seconds (30 days)